name: lab-1

on:
  push:
    branches: [lab-1]
    paths:
      - 'lab-1/**'

defaults:
  run:
    working-directory: lab-1

env:
  AZURE_FUNCTIONAPP_NAME: lab-1-node-js-artem-matiushenko
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./function

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Deploy Azure function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
